### ISSUE TITLE
Issue when Phone rotate

### ISSUE THREAD

**Issue by buzzicards** [flutterchina/azlistview#30]
Issue with the Alphabets when phone rotate on the small side...I get A RenderFlex overflowed by 200 pixels on the bottom.

Is there a way to hide alphabets or reduce the number of letters like on android phones?

Is there documentation on this?

**Comment by Sky24n** [comment]
Because IndexBar is a fixed height.
In landscape mode , you can set indexBarData = [] .

**Comment by buzzicards** [comment]
> Because IndexBar is a fixed height.
> In landscape mode , you can set indexBarData = [] .

Thanks for your quick response... is there a way to adjust the height? in case the height of the phone is smaller than the fixed height is there a good way to reduce the height? 

thanks in advance.

**Comment by Sky24n** [comment]
for example：    
 ```yaml
       //IndexBar Item Height.
      indexBarItemHeight: 20,
      // IndexBar text style. Modify the appropriate font size.
      indexBarOptions: IndexBarOptions(
        textStyle: TextStyle(fontSize: 12, color: Color(0xFF666666)),
        downTextStyle: TextStyle(fontSize: 12, color: Color(0xFF666666)),
      ),
```
